services:
    Mikoweb\SymfonyUtilityBundle\Entity\EntityFactory:
        arguments:
            - '@Mikoweb\SymfonyUtilityBundle\Entity\Provider\RendererProvider'
            - '@Mikoweb\SymfonyUtilityBundle\Entity\Provider\UrlProvider'

    Mikoweb\SymfonyUtilityBundle\EventListener\EntityProvidersSubscriber:
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    Mikoweb\SymfonyUtilityBundle\Entity\Provider\UrlProvider:
        arguments: ['@router']

    Mikoweb\SymfonyUtilityBundle\Entity\Provider\RendererProvider:
        arguments: ['@twig']
