services:
    Mikoweb\SymfonyUtilityBundle\TwigExtension\UtilitiesExtension:
        arguments:
            - '@Symfony\Contracts\Translation\TranslatorInterface'
        tags:
            - { name: twig.extension }
