services:
    symfony_utility.twig.utilities:
        class: Mikoweb\SymfonyUtilityBundle\TwigExtension\UtilitiesExtension
        calls:
            - [setContainer, ["@service_container"]]
        tags:
            - { name: twig.extension }
